# Generated by Django 4.1.7 on 2023-04-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_number', models.IntegerField(default=1, unique=True)),
                ('celestial_body', models.CharField(max_length=6)),
                ('limb', models.CharField(max_length=5)),
                ('bearing_of_body', models.CharField(max_length=5)),
                ('local_date', models.CharField(max_length=8)),
                ('local_time', models.CharField(max_length=6)),
                ('morning', models.BooleanField(default=True)),
                ('local_time_zone', models.IntegerField(default=12)),
                ('clock_error', models.IntegerField(default=0)),
                ('sextant_altitude', models.CharField(max_length=5)),
                ('eye_height', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('index_error', models.IntegerField(default=0)),
                ('temperature', models.IntegerField(default=15)),
                ('presure', models.CharField(max_length=4)),
            ],
        ),
    ]
