# Generated by Django 4.1.7 on 2023-04-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meridian_Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celestial_body', models.CharField(max_length=6)),
                ('limb', models.CharField(max_length=5)),
            ],
        ),
    ]
