# Generated by Django 4.1.7 on 2023-04-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_meridian_passage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meridian_passage',
            name='celestial_body',
            field=models.CharField(choices=[('SU', 'SUN'), ('MO', 'MOON'), ('PL', 'PLANET'), ('ST', 'STAR')], default='SU', max_length=2),
        ),
    ]
