# Generated by Django 4.1.7 on 2023-04-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0003_alter_meridian_passage_celestial_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meridian_passage',
            name='celestial_body',
            field=models.CharField(choices=[('SU', 'Sun'), ('MO', 'Moon'), ('PL', 'Planet'), ('ST', 'Star')], default='SU', max_length=2),
        ),
    ]
