# Generated by Django 4.1.7 on 2023-04-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_alter_meridian_passage_celestial_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='meridian_passage',
            name='latitude',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
