# Generated by Django 4.1.7 on 2023-04-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0005_meridian_passage_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meridian_passage',
            name='limb',
            field=models.CharField(choices=[('UP', 'Upper'), ('LO', 'Lower'), ('NA', 'Not Applicable')], default='LO', max_length=2),
        ),
    ]
