# Generated by Django 4.1.7 on 2023-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0006_alter_meridian_passage_limb'),
    ]

    operations = [
        migrations.AddField(
            model_name='meridian_passage',
            name='bearing_of_body',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South')], default='N', max_length=1),
        ),
    ]
