# Generated by Django 4.1.7 on 2023-04-10 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0007_meridian_passage_bearing_of_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='meridian_passage',
            name='local_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
