# Generated by Django 4.1.7 on 2023-04-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0009_remove_meridian_passage_local_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meridian_passage',
            name='latitude',
        ),
    ]
