# Generated by Django 4.1.7 on 2023-04-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0010_remove_meridian_passage_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='meridian_passage',
            name='local_date',
            field=models.DateField(null=True),
        ),
    ]
