# Generated by Django 4.1.7 on 2023-04-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0014_alter_meridian_passage_local_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meridian_passage',
            name='local_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
    ]
