# Generated by Django 4.1.7 on 2023-04-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0015_alter_meridian_passage_local_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meridian_passage',
            name='local_time',
            field=models.TimeField(blank=True, help_text='HH:MM', null=True),
        ),
    ]
