# Generated by Django 4.1.7 on 2023-04-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0016_meridian_passage_local_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meridian_passage',
            name='local_date',
        ),
        migrations.RemoveField(
            model_name='meridian_passage',
            name='local_time',
        ),
        migrations.AddField(
            model_name='meridian_passage',
            name='local_datetime',
            field=models.DateTimeField(blank=True, help_text='YYYY-MM-DD HH:MM:SS', null=True),
        ),
        migrations.AddField(
            model_name='meridian_passage',
            name='meridian_passage_time',
            field=models.TimeField(blank=True, help_text='HH:MM', null=True),
        ),
        migrations.AddField(
            model_name='meridian_passage',
            name='time_zone',
            field=models.IntegerField(default=12),
        ),
    ]
