# Generated by Django 4.1.7 on 2023-04-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0017_remove_meridian_passage_local_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meridian_passage',
            name='sight_number',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
