# Generated by Django 4.1.7 on 2023-04-11 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0019_meridian_passage_dr longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meridian_passage',
            old_name='DR Longitude',
            new_name='dr_longitude',
        ),
    ]
