# Generated by Django 4.1.7 on 2023-04-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0020_rename_dr longitude_meridian_passage_dr_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meridian_Passage_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_number', models.IntegerField(default=1, unique=True)),
                ('celestial_body', models.CharField(choices=[('SU', 'Sun'), ('MO', 'Moon'), ('PL', 'Planet'), ('ST', 'Star')], default='SU', max_length=2)),
                ('local_datetime', models.DateTimeField(help_text='YYYY-MM-DD HH:MM:SS')),
                ('time_zone', models.IntegerField(default=12)),
                ('utc_datetime', models.DateTimeField(help_text='YYYY-MM-DD HH:MM:SS')),
                ('meridian_passage_time', models.TimeField(help_text='HH:MM')),
                ('dr_longitude', models.CharField(default='000 00.0E', help_text='DDD MM.MX where X is either W(est) or E(ast)', max_length=9, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meridian_passage',
            name='local_datetime',
            field=models.DateTimeField(help_text='YYYY-MM-DD HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='meridian_passage',
            name='meridian_passage_time',
            field=models.TimeField(help_text='HH:MM'),
        ),
    ]
