# Generated by Django 4.1.7 on 2023-04-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0021_meridian_passage_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meridian_passage_entry',
            name='utc_datetime',
        ),
    ]
