# Generated by Django 4.1.7 on 2023-04-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0022_remove_meridian_passage_entry_utc_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meridian_passage_entry',
            old_name='local_datetime',
            new_name='passage_lmt',
        ),
        migrations.RemoveField(
            model_name='meridian_passage_entry',
            name='meridian_passage_time',
        ),
    ]
