# Generated by Django 4.1.7 on 2023-04-19 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0023_rename_local_datetime_meridian_passage_entry_passage_lmt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meridian_Passage',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='clock_error',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='local_date',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='local_time',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='local_time_zone',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='morning',
        ),
        migrations.AddField(
            model_name='sight',
            name='dec_0',
            field=models.CharField(default='-00 00.0', help_text='-DD MM.M -South +North', max_length=8),
        ),
        migrations.AddField(
            model_name='sight',
            name='dec_1',
            field=models.CharField(default='-00 00.0', help_text='-DD MM.M -South +North', max_length=8),
        ),
        migrations.AddField(
            model_name='sight',
            name='semi_diameter',
            field=models.CharField(default='00.0', help_text='MM.M', max_length=4),
        ),
        migrations.AddField(
            model_name='sight',
            name='time_of_passage_utc',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='YYYY-MM-DD HH:MM:SS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sight',
            name='bearing_of_body',
            field=models.CharField(choices=[('NO', 'North'), ('SO', 'South')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='sight',
            name='celestial_body',
            field=models.CharField(choices=[('SU', 'Sun'), ('MO', 'Moon'), ('PL', 'Planet'), ('ST', 'Star')], default='SU', max_length=2),
        ),
        migrations.AlterField(
            model_name='sight',
            name='limb',
            field=models.CharField(choices=[('UP', 'Upper'), ('LO', 'Lower'), ('NA', 'Not Applicable')], default='LO', max_length=2),
        ),
        migrations.AlterField(
            model_name='sight',
            name='sextant_altitude',
            field=models.CharField(default='00 00.0', help_text='DD MM.M', max_length=7),
        ),
    ]
