# Generated by Django 4.1.7 on 2023-04-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0024_delete_meridian_passage_remove_sight_clock_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meridian_Passage_Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_number', models.IntegerField(default=1, unique=True)),
                ('limb', models.CharField(choices=[('UP', 'Upper'), ('LO', 'Lower'), ('NA', 'Not Applicable')], default='LO', max_length=2)),
                ('bearing_of_body', models.CharField(choices=[('NO', 'North'), ('SO', 'South')], default='NO', max_length=2)),
                ('eye_height', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('index_error', models.IntegerField(default=0)),
                ('temperature', models.IntegerField(default=15)),
                ('presure', models.CharField(max_length=4)),
                ('time_of_passage_utc', models.DateTimeField(help_text='YYYY-MM-DD HH:MM:SS')),
                ('sextant_altitude', models.CharField(default='00 00.0', help_text='DD MM.M', max_length=7)),
                ('dec_0', models.CharField(default='-00 00.0', help_text='-DD MM.M -South +North', max_length=8)),
                ('dec_1', models.CharField(default='-00 00.0', help_text='-DD MM.M -South +North', max_length=8)),
                ('semi_diameter', models.CharField(default='00.0', help_text='MM.M', max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='meridian_passage_entry',
            name='limb',
            field=models.CharField(choices=[('UP', 'Upper'), ('LO', 'Lower'), ('NA', 'Not Applicable')], default='LO', max_length=2),
        ),
    ]
