# Generated by Django 4.1.7 on 2023-04-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0025_meridian_passage_sight_meridian_passage_entry_limb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meridian_passage_sight',
            name='limb',
        ),
    ]
