# Generated by Django 4.1.7 on 2023-04-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0026_remove_meridian_passage_sight_limb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sight',
        ),
    ]
