# Generated by Django 4.1.7 on 2023-04-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0027_delete_sight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meridian_passage_sight',
            name='index_error',
            field=models.CharField(default='00.0', help_text='MM.M', max_length=4),
        ),
        migrations.AlterField(
            model_name='meridian_passage_sight',
            name='presure',
            field=models.CharField(default='1013', max_length=4),
        ),
        migrations.AlterField(
            model_name='meridian_passage_sight',
            name='temperature',
            field=models.CharField(default='+15', help_text='+ or - degrees celsius', max_length=3),
        ),
    ]
