# Generated by Django 4.1.7 on 2023-04-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0028_alter_meridian_passage_sight_index_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meridian_passage_entry',
            name='celestial_body',
            field=models.CharField(choices=[('Sun', 'Sun'), ('Moon', 'Moon'), ('Planet', 'Planet'), ('Star', 'Star')], default='Sun', max_length=6),
        ),
        migrations.AlterField(
            model_name='meridian_passage_entry',
            name='limb',
            field=models.CharField(choices=[('Upper', 'Upper'), ('Lower', 'Lower'), ('Not Applicable', 'Not Applicable')], default='Lower', max_length=14),
        ),
    ]
