# Generated by Django 4.1.7 on 2023-04-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0029_alter_meridian_passage_entry_celestial_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meridian_passage_sight',
            name='bearing_of_body',
            field=models.CharField(choices=[('North', 'North'), ('South', 'South')], default='North', max_length=5),
        ),
    ]
