# Generated by Django 4.1.7 on 2023-04-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0030_alter_meridian_passage_sight_bearing_of_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meridian_passage_sight',
            old_name='sextant_altitude',
            new_name='height_sextant',
        ),
    ]
