# Generated by Django 4.1.7 on 2023-04-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0031_rename_sextant_altitude_meridian_passage_sight_height_sextant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meridian_passage_sight',
            old_name='presure',
            new_name='pressure',
        ),
    ]
