# Generated by Django 4.1.7 on 2023-04-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0033_alter_meridian_passage_sight_index_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meridian_passage_sight',
            name='eye_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='meridian_passage_sight',
            name='index_error',
            field=models.CharField(default='+00.0', help_text='+MM.M + = off arc, - = on arc', max_length=5),
        ),
    ]
