# Generated by Django 4.1.7 on 2023-05-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0035_remove_meridian_passage_sight_time_of_passage_utc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunriseSunsetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_number', models.IntegerField(default=1, unique=True)),
                ('day', models.DateField(help_text='YYYY-MM-DD')),
                ('time_zone', models.IntegerField(default=12)),
                ('latitude', models.CharField(default='000 00.0S', help_text='DD MM.MX where X is either N(orth) or S(outh)', max_length=8, null=True)),
                ('longitude', models.CharField(default='000 00.0E', help_text='DDD MM.MX where X is either W(est) or E(ast)', max_length=9, null=True)),
            ],
        ),
    ]
