# Generated by Django 4.1.7 on 2023-05-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0036_sunrisesunsetentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunrisesunsetentry',
            name='latitude',
            field=models.CharField(default='00 00.0S', help_text='DD MM.MX where X is either N(orth) or S(outh)', max_length=8, null=True),
        ),
    ]
