# Generated by Django 4.1.7 on 2023-05-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0037_alter_sunrisesunsetentry_latitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_number', models.IntegerField(default=1, unique=True)),
                ('celestial_body', models.CharField(choices=[('Sun', 'Sun'), ('Moon', 'Moon'), ('Planet', 'Planet'), ('Star', 'Star')], default='Sun', max_length=6)),
                ('limb', models.CharField(choices=[('Upper', 'Upper'), ('Lower', 'Lower'), ('Not Applicable', 'Not Applicable')], default='Lower', max_length=14)),
                ('sight_time_lmt', models.DateTimeField(help_text='YYYY-MM-DD HH:MM:SS')),
                ('time_zone', models.IntegerField(default=12)),
                ('dr_longitude', models.CharField(default='000 00.0E', help_text='DDD MM.MX where X is either W(est) or E(ast)', max_length=9, null=True)),
                ('dr_latitude', models.CharField(default='00 00.0S', help_text='DD MM.MX where X is either S(outh) or N(orth)', max_length=8, null=True)),
                ('eye_height', models.FloatField(default=0.0)),
                ('index_error', models.CharField(default='+00.0', help_text='+MM.M + = off arc, - = on arc', max_length=5)),
                ('temperature', models.CharField(default='+15', help_text='+ or - degrees celsius', max_length=3)),
                ('pressure', models.CharField(default='1013', max_length=4)),
                ('height_sextant', models.CharField(default='00 00.0', help_text='DD MM.M', max_length=7)),
                ('morning', models.BooleanField(default=True)),
                ('clock_error', models.CharField(default='-000', help_text='-SSS secounds -slow, +fast', max_length=4)),
                ('dec_0', models.CharField(default='-00 00.0', help_text='-DD MM.M -South +North', max_length=8)),
                ('dec_1', models.CharField(default='-00 00.0', help_text='-DD MM.M -South +North', max_length=8)),
                ('gha_0', models.CharField(default='000 00.0', help_text='DDD MM.M', max_length=8)),
                ('gha_1', models.CharField(default='000 00.0', help_text='DDD MM.M', max_length=8)),
                ('sha', models.CharField(default='000 00.0', help_text='DDD MM.M', max_length=8)),
                ('semi_diameter', models.CharField(default='00.0', help_text='MM.M', max_length=4)),
            ],
        ),
    ]
