# Generated by Django 4.1.7 on 2023-05-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0038_sightentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meridian_passage_entry',
            name='dr_longitude',
            field=models.CharField(default='000 00.0E', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='meridian_passage_entry',
            name='passage_lmt',
            field=models.DateTimeField(default='2023-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='sightentry',
            name='clock_error',
            field=models.CharField(default='-000', help_text='-SSS seconds -slow, +fast', max_length=4),
        ),
    ]
