# Generated by Django 4.1.7 on 2023-06-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0040_sightalmanacentry_remove_sightentry_dec_0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarFinderGhaAries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_number', models.IntegerField(default=1, unique=True)),
                ('gha_0', models.CharField(default='000 00.0', help_text='DDD MM.M', max_length=8)),
                ('gha_1', models.CharField(default='000 00.0', help_text='DDD MM.M', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='StarFinderTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_number', models.IntegerField(default=1, unique=True)),
                ('sight_time_lmt', models.DateTimeField(help_text='YYYY-MM-DD HH:MM:SS')),
                ('time_zone', models.IntegerField(default=12)),
                ('dr_longitude', models.CharField(default='000 00.0E', help_text='DDD MM.MX where X is either W(est) or E(ast)', max_length=9, null=True)),
            ],
        ),
    ]
